In [1]:
import jovian

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [90]:
# List of functions explained 
function1 = np.arange  
function2 = np.diag
function3 = np.reshape
function4 = np.sort
function5 = np.linspace

## Function 1 - np.arange

np.arange function is work how range function work in python but returns an ndarray rather than a list. In np.arange we mantion stating and endpoin we can also give different step in np.arange.

In [4]:
# Example 1 
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In Example 1 we create a array of 9 elements of int type by specifing starting and end index

In [5]:
# Example 2 - working
arr2 = np.arange(10,30,3)
arr2

array([10, 13, 16, 19, 22, 25, 28])

In Example 2 we create a array of 7 elements of int type by specifing starting and end index also the steps

In [6]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.range(10.,30,40)
arr3

AttributeError: module 'numpy' has no attribute 'range'

In Example 3 function breaks because of wrong function name range does not exist in numpy, some time we use range instead of arange.
we can fix it by using write function name

Some closing comments about when to use this function.

## Function 2 -   np.diag

The diag() function is used to construct a diagonal 2-d array with a numpy library. It contains two parameters: an input array and k, which decides the diagonal.It is the numpy library function, which is used to perform the mathematical operation on the multidimensional array.

In [12]:
# Example 1 - working
arr =  np.array([[2,2,3],[1,5,6],[4,6,7]])
np.diag(arr)

array([2, 5, 7])

In Example 1 a 2d array is given we find the diagnal of that array using np.diag function.

In [18]:
# Example 2 - working
arr1 = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
print("Main diagonal : ",np.diag(arr1,k=1))

Main diagonal :  [2 6]


In this example, we will be printing the upper diagonal of the main diagonal. In this, we will pass the k parameter with the positive value of k to give us the upper diagonal. By applying the numpy diag() function, we will print the upper diagonal.for lower diagnal we padd a negative integer

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = [[[1,2,3],[2,4,5],[4,6,4]]]
np.diag(arr2)

ValueError: Input must be 1- or 2-d.

The diag() function is used to extract and construct a diagonal 2-d array or 1d array with a numpy library. while i pass a 3d here thats why this break. to fix that we use np.diagonal() function.

np.diag() function ud used when we need a 2d array diagonal or when he create a 2d array with specific diagnoal 

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ajmehdi5/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/ajmehdi5/numpy-array-operations


'https://jovian.ai/ajmehdi5/numpy-array-operations'

## Function 3 - np.reshape

- Reshaping means changing the shape of an array.
- The shape of an array is the number of elements in each dimension.
- Reshaping we can add or remove dimensions or change number of elements in each dimension.

``` numpy.reshape(a, new shape, order=’C’) ```
- a: It is the array that we want to reshape.
- New shape: It is the shape that we want to reshape our old array into.We should keep in mind is that the new shape given should be compatible with the old shape. You cannot change the 2×3 array into a 1×7
    For example, if you have an array of size – (2,3) =6 elements, you can only change it to a new array, which can contain six elements like 1×6, 3×2, 6×1.
- order: {‘C’,’A’,’F’ ; optional} Using this parameter we can read elements of an array in a particular order(index).
        ‘C’ means that operating row-wise.
        ‘F’ means Fortran style, and column-wise.
        ‘A’ means Fortran-like order if memory management same as ‘F’, C style otherwise.

In [25]:
# Example 1 - working
arr = np.array([1,2,3,4,5,6,7,8])

# reshaping the array into array with 2 rows and 4 columns
arr1 = np.reshape(arr,(2,4))

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In example Example 1 we convert 1 1d araay into 2d array 

In [30]:
# Example 2 - working
arr = np.array([[1, 2, 3], [4, 5, 6]])
# arr1 = np.reshape(arr,-1)
arr1 = arr.reshape(-1)
arr1

array([1, 2, 3, 4, 5, 6])

In Example 2 we convert 2d array into 1d array by passing -1 argument in reshape method we can pass arr in reshape as argument also we can call reshape method with array 

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

This break because element in 1d array is not enough to convert into a 3 by 3 matrix, this can be fixing by adding one more element in the array

Numpy reshape is very useful function we use it alot in owr working 

In [34]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ajmehdi5/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/ajmehdi5/numpy-array-operations


'https://jovian.ai/ajmehdi5/numpy-array-operations'

## Function 4- np.sort

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending

In [83]:
# Example 1 - working
arr = np.array([[12, 15], [10, 1]])
arr1 = np.sort(arr, axis = 0)        
print ("Along first axis : \n", arr1)        
 
# sort along the last axis
arr = np.array([[10, 15], [12, 1]])
arr2 = np.sort(arr, axis = -1)        
print ("\nAlong last axis : \n", arr2)
 
arr = np.array([[12, 15], [10, 1]])
arr3 = np.sort(a, axis = None)        
print ("\nAlong none axis : \n", arr3)
print(arr3.shape)

# sort 1d aray
arr4 = np.array([1,14,5,56,785,43])
print("1d array sort :{}".format(np.sort(arr3)))

Along first axis : 
 [[10  1]
 [12 15]]

Along last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]
(4,)
1d array sort :[ 1 10 12 15]


In Example 1 we see how to sort a array in diffenrt axis we also see how a 1d array sort in assending order

In [64]:
# Example 2 - working
arr = np.array(['banana', 'cherry', 'apple','dates'])
arr.sort()
arr1

array(['apple', 'banana', 'cherry', 'dates'], dtype='<U6')

In Exapmle 2 we sort a array in alphabetical order using sort method

In [86]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[12, 15], [10, 1]])
arr1 = np.sort(a, axis = 2)
arr1

AxisError: axis 2 is out of bounds for array of dimension 2

This breaks becase of axis = 2 as array is 2 by 2 we pcan pass only -1,0 and 1 so in order to correct this we have to pass 1 or 0 

sort is a useful function is is fast a work for all kind of array 

In [87]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ajmehdi5/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/ajmehdi5/numpy-array-operations


'https://jovian.ai/ajmehdi5/numpy-array-operations'

## Function 5 - np.linspace() 
Function returns evenly spaced numbers over a specified interval defined by the first two arguments of the function

In [102]:
# Example 1 - working
print("Restep True", np.linspace(2.0, 3.0, num=4, retstep=True))
np.linspace(2.0, 3.0, num=4)

Restep True (array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)


array([2.        , 2.33333333, 2.66666667, 3.        ])

As linespace funtion return evenly spaced number between interval returened number we specify in argument restep by default False we make it True to see the step between number

In [104]:
# Example 2 - working
np.linspace(2.0, 3.0,endpoint = False)

array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
       2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
       2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
       2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
       2.88, 2.9 , 2.92, 2.94, 2.96, 2.98])

When end point false it not include endpoin by default it is True

In [105]:
# Example 3 - breaking (to illustrate when it breaks)
np.linspace([2.0, 3.0],endpoint = False)

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

linespace() only work with number i.e with intervals not with array, we pass here a array thas why its break we fix it by passing intervel

it is a very useful funtion we use it when we need a eqully distance points in our project

In [106]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ajmehdi5/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/ajmehdi5/numpy-array-operations


'https://jovian.ai/ajmehdi5/numpy-array-operations'

## Conclusion

Covere some very useful numpy function which make owr work easy.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy diag and diagonal method explanation : https://www.pythonpool.com/numpy-diag/
* Numpy different function with explanation : https://www.w3schools.com/python/numpy/default.asp

In [107]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ajmehdi5/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/ajmehdi5/numpy-array-operations


'https://jovian.ai/ajmehdi5/numpy-array-operations'